author: Roger Gros
description: |
    Google analytics integration for your shop
year: 2015
name: Google Analytics
url: http://www.google.com/analytics/
fa_icon: google
configuration_route: admin_google_analytics_configuration
version: ~0.4
enabled: false
visible: true
