plugin:
    type: plugin
    name: Google Analytics
    description: |
        Google analytics integration for your shop
    fa_icon: google
    fields:
        analytics_tracker_id:
            type: text
            required: true
            label: elcodi_plugin.google_analytics.analytics_tracker_id
