author: Roger Gros
description: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Mauris ac nibh a eros auctor lobortis. Etiam pellentesque diam nibh, id sagittis nisi finibus ac.
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
    In accumsan leo in neque dictum, quis mattis ligula consectetur
year: 2015
name: Google Analytics
url: http://url-ga.com
fa_icon: google
configuration_route: admin_google_analytics_configuration
version: ~0.4
visible: true
